import { task } from "@trigger.dev/sdk/v3";
import { OpenAI } from "openai";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import * as zodToJsonSchema from "zod-to-json-schema";
import { toFile } from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const ProjectSchema = z.object({
    client_name: z.string().describe("Le nom et/ou prénom du client. Inconnu si non spécifié."),
    client_phone: z.string().describe("Le numéro de téléphone du client s'il est mentionné. Laisser vide si non trouvé."),
    client_address: z.string().describe("L'adresse complète de l'intervention ou du client. Laisser vide si non trouvée."),
    project_title: z.string().describe("Un titre court, pro et clair pour le chantier (ex: Rénovation Salle de Bain). C'est le nom du projet."),
    description: z.string().describe("Un résumé détaillé de ce qu'il faut faire sur ce chantier, en gardant toutes les cotes ou mesures citées."),
    budget_estimate: z.number().nullable().describe("Le budget estimé ou le montant total HT s'il est mentionné. Sinon null."),
});

export const createProjectAudioTask = task({
    id: "create-project-audio",
    maxDuration: 120,
    retry: {
        maxAttempts: 3,
        minTimeoutInMs: 1000,
        maxTimeoutInMs: 10000,
        factor: 2,
        randomize: true,
    },
    run: async (payload: { storageUrl: string; organizationId: string }) => {
        try {
            // 1. Download the audio file from Supabase Storage as a stream for OOM safety
            const response = await fetch(payload.storageUrl);

            // Stream the web response directly to an OpenAI File rather than buffering ArrayBuffer
            const audioFile = await toFile(response, "audio.webm", { type: "audio/webm" });

            // 2. Transcribe Audio with Whisper
            const transcription = await openai.audio.transcriptions.create({
                file: audioFile,
                model: "whisper-1",
            });

            const transcriptText = transcription.text;
            console.log("Transcription:", transcriptText);

            // 3. Extract structured data using GPT-4o
            const extractionResult = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [
                    {
                        role: "system",
                        content: `Tu es l'assistant IA "OptiPro" pour un artisan. Un artisan vient d'enregistrer une note vocale pour créer un NOUVEAU chantier.
Tu dois extraire de sa transcription toutes les informations utiles pour créer la fiche Client et la fiche Projet dans la base de données.
S'il manque des informations comme l'adresse ou le téléphone, laisse-les vides. Le client peut être une entreprise ou un particulier.
Invente un 'project_title' clair basé sur la description si l'artisan n'a pas donné de nom précis au chantier.
`
                    },
                    {
                        role: "user",
                        content: `Voici la transcription de la note vocale de l'artisan : "${transcriptText}"`
                    }
                ],
                response_format: {
                    type: "json_schema",
                    json_schema: {
                        name: "project_extraction",
                        schema: zodToJsonSchema.zodToJsonSchema(ProjectSchema as unknown as Parameters<typeof zodToJsonSchema.zodToJsonSchema>[0], "project_extraction") as Record<string, unknown>,
                        strict: true
                    }
                }
            });

            const rawContent = extractionResult.choices[0].message.content;
            if (!rawContent) throw new Error("No content generated by GPT-4o");

            const result = JSON.parse(rawContent);
            console.log("Extracted Project Data:", result);

            // 4. Save to Database
            // Step A: Upsert Client
            let clientId: string;

            // Check if client exists (simple name search for V1)
            const { data: existingClient } = await supabase
                .from("clients")
                .select("id")
                .eq("organization_id", payload.organizationId)
                .ilike("name", result.client_name)
                .maybeSingle();

            if (existingClient) {
                clientId = existingClient.id;
                // Optional: We could update the address or phone here if it was missing
            } else {
                // Create new client
                const { data: newClient, error: clientErr } = await supabase
                    .from("clients")
                    .insert({
                        organization_id: payload.organizationId,
                        name: result.client_name === "Inconnu" ? "Client Inconnu" : result.client_name,
                        email: null, // Hard to get via voice
                        phone: result.client_phone || null,
                        address: result.client_address || null
                    })
                    .select("id")
                    .single();

                if (clientErr) throw new Error(`Client creation failed: ${clientErr.message}`);
                clientId = newClient.id;
            }

            // Step B: Create Project
            const { data: newProject, error: projectErr } = await supabase
                .from("projects")
                .insert({
                    organization_id: payload.organizationId,
                    client_id: clientId,
                    title: result.project_title,
                    description: result.description,
                    status: "DEVIS", // Always default to DEVIS for a new Voice Lead
                    budget: result.budget_estimate || 0,
                    total_ht: result.budget_estimate || 0,
                })
                .select("id")
                .single();

            if (projectErr) throw new Error(`Project creation failed: ${projectErr.message}`);

            return {
                success: true,
                project_id: newProject.id,
                client_id: clientId,
                title: result.project_title,
                transcript: transcriptText
            };

        } catch (error: unknown) {
            const err = error as Error;
            console.error("Task Failed:", err.message);
            throw err;
        }
    },
});
