import { createClient } from "@/utils/supabase/server";
import { getEffectiveOrgId } from "@/utils/auth";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Mail, Phone, MapPin, FolderKanban, MoreVertical, Plus } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { notFound } from "next/navigation";

// Utility to render project statuses
function getStatusBadge(status: string) {
    switch (status) {
        case 'DEVIS':
            return <Badge variant="outline" className="text-secondary-foreground border-border px-3 py-1 font-semibold bg-secondary/50">Devis</Badge>;
        case 'EN_COURS':
            return <Badge className="bg-primary/10 text-primary hover:bg-primary/20 border-0 px-3 py-1 font-semibold">En cours</Badge>;
        case 'TERMINE':
            return <Badge className="bg-success/10 text-success hover:bg-success/20 border-0 px-3 py-1 font-semibold">Terminé</Badge>;
        case 'ARCHIVE':
            return <Badge variant="secondary" className="opacity-50 px-3 py-1 font-semibold">Archivé</Badge>;
        default:
            return null;
    }
}

export default async function ClientDetailPage(props: { params: Promise<{ id: string }> }) {
    const params = await props.params;
    const clientId = params.id;
    const supabase = await createClient();
    const orgId = await getEffectiveOrgId();

    // 1. Fetch Client Profile
    const { data: clientResp, error: clientError } = await supabase
        .from('clients')
        .select('*')
        .eq('id', clientId)
        .eq('organization_id', orgId)
        .single();

    if (clientError || !clientResp) {
        console.error("Client fetch error:", clientError);
        notFound();
    }

    const client = clientResp as any;

    // 2. Fetch Client's Projects
    const { data: projects, error: projectsError } = await supabase
        .from('projects')
        .select('*')
        .eq('client_id', clientId)
        .eq('organization_id', orgId)
        .order('created_at', { ascending: false });

    if (projectsError) {
        console.error("Projects fetch error:", projectsError);
    }

    const projectsList = projects as any[] || [];

    // Calculate total revenue generated by this client
    const totalRevenue = projectsList.reduce((acc, p) => acc + (p.total_ht || 0), 0);

    return (
        <div className="p-4 flex flex-col gap-6 pb-28 min-h-screen bg-background">
            <header className="flex items-center gap-3 mt-2">
                <Link href="/clients">
                    <Button variant="ghost" size="icon" className="rounded-xl w-10 h-10 shrink-0 hover:bg-muted text-muted-foreground">
                        <ArrowLeft className="w-5 h-5" />
                    </Button>
                </Link>
                <div>
                    <h1 className="text-xl font-bold tracking-tight">Fiche Client</h1>
                </div>
            </header>

            {/* Client Profile Card */}
            <Card className="border-border bg-card shadow-sm rounded-2xl overflow-hidden">
                <div className="h-20 bg-primary/10 relative">
                    {/* Decorative Header */}
                </div>
                <CardContent className="p-5 pt-0 relative flex flex-col gap-5">
                    <div className="flex justify-between items-end -mt-10 mb-2">
                        <div className="w-20 h-20 bg-background rounded-full p-1.5 shadow-sm">
                            <div className="w-full h-full rounded-full bg-primary/20 text-primary flex items-center justify-center font-black text-3xl">
                                {client.name.charAt(0).toUpperCase()}
                            </div>
                        </div>
                        <div className="text-right">
                            <p className="text-[11px] font-bold text-muted-foreground uppercase tracking-wide">CA Total</p>
                            <p className="font-black text-xl text-primary">{totalRevenue.toLocaleString('fr-FR')} €</p>
                        </div>
                    </div>

                    <div>
                        <h2 className="text-2xl font-black tracking-tight leading-none mb-1">{client.name}</h2>
                        <p className="text-sm text-muted-foreground font-medium">Créé le {new Date(client.created_at).toLocaleDateString('fr-FR')}</p>
                    </div>

                    {/* Contact Links */}
                    <div className="flex flex-col gap-3 bg-secondary/30 p-4 rounded-xl border border-border">
                        {client.email && (
                            <a href={`mailto:${client.email}`} className="flex items-center justify-between text-sm font-semibold text-foreground hover:text-primary transition-colors">
                                <span className="flex items-center gap-2"><Mail className="w-4 h-4 text-primary" /> Email</span>
                                <span>{client.email}</span>
                            </a>
                        )}
                        {client.phone && (
                            <a href={`tel:${client.phone}`} className="flex items-center justify-between text-sm font-semibold text-foreground hover:text-primary transition-colors">
                                <span className="flex items-center gap-2"><Phone className="w-4 h-4 text-primary" /> Téléphone</span>
                                <span>{client.phone}</span>
                            </a>
                        )}
                        {client.address && (
                            <div className="flex items-start justify-between text-sm font-semibold text-foreground pt-1">
                                <span className="flex items-center gap-2 pt-0.5"><MapPin className="w-4 h-4 text-primary shrink-0" /> Adresse</span>
                                <span className="text-right max-w-[180px] break-words whitespace-pre-wrap">{client.address}</span>
                            </div>
                        )}
                    </div>
                </CardContent>
            </Card>

            {/* Client's Projects */}
            <div>
                <div className="flex justify-between items-center mb-4">
                    <h3 className="text-lg font-bold flex items-center gap-2">
                        <FolderKanban className="w-5 h-5 text-primary" /> Chantiers liés
                    </h3>
                    <Link href={`/projects/new?client_id=${client.id}`}>
                        <Button variant="outline" size="sm" className="h-8 shadow-sm gap-1.5 rounded-lg text-xs font-semibold">
                            <Plus className="w-3.5 h-3.5" /> Créer
                        </Button>
                    </Link>
                </div>

                <div className="flex flex-col gap-3">
                    {projectsList.length === 0 ? (
                        <div className="text-center py-8 text-muted-foreground border border-dashed border-border rounded-xl bg-secondary/30 text-sm">
                            Ce client n'a aucun projet/chantier.
                        </div>
                    ) : (
                        projectsList.map((project) => (
                            <Link href={`/projects/${project.id}`} key={project.id}>
                                <Card className="overflow-hidden border-border bg-card shadow-sm rounded-xl hover:border-primary/50 hover:shadow-md transition-all cursor-pointer">
                                    <CardContent className="p-4 flex flex-col gap-2">
                                        <div className="flex justify-between items-start">
                                            <h4 className="font-bold text-[15px] leading-tight flex-1 pr-4">{project.title}</h4>
                                            <div className="shrink-0">{getStatusBadge(project.status || '')}</div>
                                        </div>
                                        <div className="flex justify-between items-end mt-1">
                                            <span className="text-xs font-medium text-muted-foreground">Créé le {new Date(project.created_at).toLocaleDateString('fr-FR')}</span>
                                            <span className="font-black text-lg">{(project.total_ht || 0).toLocaleString('fr-FR')} €</span>
                                        </div>
                                    </CardContent>
                                </Card>
                            </Link>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}
